name: Shop
version: '3.0.0'
main: main.shop.Shop
api-version: '1.21'
author: Macsig74
depend: [Essentials]

commands:
  shop:
    usage: /shop
    description: Ouvre le shop
  spawn:
    usage: /spawn
    description: Téléporte au spawn
  setspawn:
    usage: /setspawn
    description: Définit le spawn
  afk:
    usage: /afk
    description: Téléporte en zone AFK
  setafk:
    usage: /setafk
    description: Définit la zone AFK

  macsigcore:
    usage: /macsigcore reload
    description: Recharge la config

  shard:
    usage: /shard <give|take|set|dump> <player> [amount]
    description: Gère les shards
  rtp:
    usage: /rtp
    description: Téléportation aléatoire

  discord:
    usage: /discord
    description: donne lien serveur discord

  store:
    usage: /store
    description:  donne lien store

  media:
    usage: /media
    description: /condition pour media

  soutien:
    usage: /soutien
    description: conditions grades soutien

  rules:
    usage: /rules
    description: donne les règles

  message:
    usage: /message
    description: Changer ses messages custom