name: Shop
version: '1.0'
main: main.shop.Shop
api-version: '1.21'
author: Macsig74
depend: [Essentials]

commands:
  shop:
    usage: /shop
    description: Ouvre le shop
  spawn:
    usage: /spawn
    description: Téléporte au spawn
  setspawn:
    usage: /setspawn
    description: Définit le spawn
  afk:
    usage: /afk
    description: Téléporte en zone AFK
  setafk:
    usage: /setafk
    description: Définit la zone AFK